# Pandas

In [29]:
import pandas as pd

In [30]:
pd.__version__

'2.2.2'

In [31]:
store=pd.read_csv(r"D:\FSDS\20th(mar25)-pandas\20th, 21st\DataFrame_ Pandas\Sample - Superstore_Orders.csv")

In [32]:
store

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [33]:
id(store) # it displays the address

2258789508640

In [34]:
len(store) # it gives only rows

10194

In [35]:
store.columns # it displays the all column names in dataset.

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [36]:
len(store.columns)

19

In [37]:
store.isnull()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [38]:
store.isnull().sum()

Category          0
City              0
Country/Region    0
Customer Name     0
Manufacturer      0
Order Date        0
Order ID          0
Postal Code       0
Product Name      0
Region            0
Segment           0
Ship Date         0
Ship Mode         0
State/Province    0
Sub-Category      0
Discount          0
Profit            0
Quantity          0
Sales             0
dtype: int64

In [39]:
store.shape   # it displays the rows & columns

(10194, 19)

In [40]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
 15  Discount        10194 non-null  float64
 16  Profit          10194 non-null  float64
 17  Quantity        10194 non-null  int64
 18  Sales           10194 non-null  float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [41]:
store[:]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [42]:
store[0:10]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
6,Office Supplies,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Handheld Barrel Pencil Sharpener,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.0,1.4796,2,5.480
7,Office Supplies,Athens,United States,Jack O'Briant,Dixon,06-01-2020,US-2020-106054,30605,"Dixon Prang Watercolor Pencils, 10-Color Set w...",South,Corporate,07-01-2020,First Class,Georgia,Art,0.0,5.2398,3,12.780
8,Office Supplies,Henderson,United States,Maria Etezadi,Ibico,06-01-2020,US-2020-167199,42420,Ibico Hi-Tech Manual Binding System,South,Home Office,10-01-2020,Standard Class,Kentucky,Binders,0.0,274.4910,2,609.980
9,Office Supplies,Henderson,United States,Maria Etezadi,Alliance,06-01-2020,US-2020-167199,42420,"Alliance Super-Size Bands, Assorted Sizes",South,Home Office,10-01-2020,Standard Class,Kentucky,Fasteners,0.0,0.3112,4,31.120

In [43]:
store[0:20:5]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
10,Office Supplies,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth 25% Cotton Granite Paper & Envelopes,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
15,Office Supplies,Huntsville,United States,Vivek Sundaresam,Acco,07-01-2020,US-2020-105417,77340,Acco Four Pocket Poly Ring Binder with Label H...,Central,Consumer,12-01-2020,Standard Class,Texas,Binders,0.8,-18.2525,7,10.430

In [44]:
store.head() # it displays the top 5 rows

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536

In [45]:
store.head(3)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784

In [46]:
store.tail() # it displays the bottom rows of dataset.

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [47]:
store.tail(3)

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [48]:
store.isna() #isna() & isnull() both are same.

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10190,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10191,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10192,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
10193,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

# statistical concepts in pandas

In [50]:
store.describe() # it displays the number(numerical data columns)

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

In [51]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [52]:
store['Category']

0        Office Supplies
1        Office Supplies
2        Office Supplies
3        Office Supplies
4        Office Supplies
              ...
10189    Office Supplies
10190    Office Supplies
10191    Office Supplies
10192         Technology
10193    Office Supplies
Name: Category, Length: 10194, dtype: object

In [53]:
store[['Category','City']] # two square brackets we should add

              Category           City
0      Office Supplies        Houston
1      Office Supplies     Naperville
2      Office Supplies     Naperville
3      Office Supplies     Naperville
4      Office Supplies   Philadelphia
...                ...            ...
10189  Office Supplies  New York City
10190  Office Supplies      Fairfield
10191  Office Supplies       Loveland
10192       Technology  New York City
10193  Office Supplies  Charlottetown

[10194 rows x 2 columns]

In [54]:
store[['Category','City','Customer Name']] # two square brackets we should add

              Category           City      Customer Name
0      Office Supplies        Houston      Darren Powers
1      Office Supplies     Naperville      Phillina Ober
2      Office Supplies     Naperville      Phillina Ober
3      Office Supplies     Naperville      Phillina Ober
4      Office Supplies   Philadelphia         Mick Brown
...                ...            ...                ...
10189  Office Supplies  New York City  Patrick O'Donnell
10190  Office Supplies      Fairfield         Erica Bern
10191  Office Supplies       Loveland      Jill Matthias
10192       Technology  New York City  Patrick O'Donnell
10193  Office Supplies  Charlottetown        Harry Olson

[10194 rows x 3 columns]

In [55]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [56]:
Store_cat=store[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category']]
Store_cat

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders

In [125]:
Store_cat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
dtypes: object(15)
memory usage: 1.2+ MB

In [127]:
store.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        10194 non-null  object
 1   City            10194 non-null  object
 2   Country/Region  10194 non-null  object
 3   Customer Name   10194 non-null  object
 4   Manufacturer    10194 non-null  object
 5   Order Date      10194 non-null  object
 6   Order ID        10194 non-null  object
 7   Postal Code     10194 non-null  object
 8   Product Name    10194 non-null  object
 9   Region          10194 non-null  object
 10  Segment         10194 non-null  object
 11  Ship Date       10194 non-null  object
 12  Ship Mode       10194 non-null  object
 13  State/Province  10194 non-null  object
 14  Sub-Category    10194 non-null  object
 15  Discount        10194 non-null  float64
 16  Profit          10194 non-null  float64
 17  Quantity        10194 non-null  int64
 18  Sales           10194 non-null  float64
dtypes: float64(3), int64(1), object(15)
memory usage: 1.5+ MB

In [129]:
len(Store_cat.columns)

15

In [60]:
len(store.columns)

19

In [61]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [62]:
Store_num=store[['Discount', 'Profit', 'Quantity', 'Sales']]
Store_num

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [63]:
Store_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Discount  10194 non-null  float64
 1   Profit    10194 non-null  float64
 2   Quantity  10194 non-null  int64
 3   Sales     10194 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 318.7 KB

In [64]:
print(len(store.columns))
print(len(Store_cat.columns))
print(len(Store_num.columns))

19
15
4

In [123]:
Store_cat.describe()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category
count,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194,10194
unique,3,542,2,800,183,1242,5111,655,1849,4,3,1338,4,59,17
top,Office Supplies,New York City,United States,William Brown,Other,05-09-2022,US-2023-100111,10035,Staples,West,Consumer,16-12-2021,Standard Class,California,Binders
freq,6128,915,9994,41,1940,38,14,263,50,3253,5281,38,6120,2001,1548

In [66]:
Store_num.describe()

           Discount        Profit      Quantity         Sales
count  10194.000000  10194.000000  10194.000000  10194.000000
mean       0.155385     28.673417      3.791838    228.225854
std        0.206249    232.465115      2.228317    619.906839
min        0.000000  -6599.978000      1.000000      0.444000
25%        0.000000      1.760800      2.000000     17.220000
50%        0.200000      8.690000      3.000000     53.910000
75%        0.200000     29.297925      5.000000    209.500000
max        0.800000   8399.976000     14.000000  22638.480000

In [105]:
store.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
Discount,10194.0,0.155385,0.206249,0.000,0.0000,0.20,0.200000,0.800
Profit,10194.0,28.673417,232.465115,-6599.978,1.7608,8.69,29.297925,8399.976
Quantity,10194.0,3.791838,2.228317,1.000,2.0000,3.00,5.000000,14.000
Sales,10194.0,228.225854,619.906839,0.444,17.2200,53.91,209.500000,22638.480

In [109]:
store.describe().T # Both are same

,count,mean,std,min,25%,50%,75%,max
Discount,10194.0,0.155385,0.206249,0.000,0.0000,0.20,0.200000,0.800
Profit,10194.0,28.673417,232.465115,-6599.978,1.7608,8.69,29.297925,8399.976
Quantity,10194.0,3.791838,2.228317,1.000,2.0000,3.00,5.000000,14.000
Sales,10194.0,228.225854,619.906839,0.444,17.2200,53.91,209.500000,22638.480

In [111]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [117]:
len(store.columns)

19

In [119]:
store.dtypes

Category           object
City               object
Country/Region     object
Customer Name      object
Manufacturer       object
Order Date         object
Order ID           object
Postal Code        object
Product Name       object
Region             object
Segment            object
Ship Date          object
Ship Mode          object
State/Province     object
Sub-Category       object
Discount          float64
Profit            float64
Quantity            int64
Sales             float64
dtype: object

In [121]:
store[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code']]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143
...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A

In [131]:
Store_cat.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category'],
      dtype='object')

In [133]:
Store_cat[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer']]

,Category,City,Country/Region,Customer Name,Manufacturer
0,Office Supplies,Houston,United States,Darren Powers,Message Book
1,Office Supplies,Naperville,United States,Phillina Ober,GBC
2,Office Supplies,Naperville,United States,Phillina Ober,Avery
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery
...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC
10191,Office Supplies,Loveland,United States,Jill Matthias,Other
10192,Technology,New York City,United States,Patrick O'Donnell,Other
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones

In [135]:
store[:]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024

In [137]:
store[1:10]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
5,Furniture,Henderson,United States,Maria Etezadi,Global,06-01-2020,US-2020-167199,42420,Global Deluxe High-Back Manager's Chair,South,Home Office,10-01-2020,Standard Class,Kentucky,Chairs,0.0,746.4078,9,2573.820
6,Office Supplies,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Handheld Barrel Pencil Sharpener,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.0,1.4796,2,5.480
7,Office Supplies,Athens,United States,Jack O'Briant,Dixon,06-01-2020,US-2020-106054,30605,"Dixon Prang Watercolor Pencils, 10-Color Set w...",South,Corporate,07-01-2020,First Class,Georgia,Art,0.0,5.2398,3,12.780
8,Office Supplies,Henderson,United States,Maria Etezadi,Ibico,06-01-2020,US-2020-167199,42420,Ibico Hi-Tech Manual Binding System,South,Home Office,10-01-2020,Standard Class,Kentucky,Binders,0.0,274.4910,2,609.980
9,Office Supplies,Henderson,United States,Maria Etezadi,Alliance,06-01-2020,US-2020-167199,42420,"Alliance Super-Size Bands, Assorted Sizes",South,Home Office,10-01-2020,Standard Class,Kentucky,Fasteners,0.0,0.3112,4,31.120

In [141]:
store[0:50:10]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
10,Office Supplies,Henderson,United States,Maria Etezadi,Southworth,06-01-2020,US-2020-167199,42420,Southworth 25% Cotton Granite Paper & Envelopes,South,Home Office,10-01-2020,Standard Class,Kentucky,Paper,0.0,3.0084,1,6.540
20,Furniture,Dover,United States,Seth Vernon,DAX,11-01-2020,US-2020-130092,19901,"DAX Value U-Channel Document Frames, Easel Back",East,Consumer,14-01-2020,First Class,Delaware,Furnishings,0.0,3.0814,2,9.940
30,Office Supplies,San Francisco,United States,Brian Dahlen,Tennsco,13-01-2020,US-2020-157147,94109,Tennsco 6- and 18-Compartment Lockers,West,Consumer,18-01-2020,Standard Class,California,Storage,0.0,238.6530,5,1325.850
40,Office Supplies,Scottsdale,United States,Toby Swindell,GBC,19-01-2020,US-2020-146591,85254,"GBC Standard Recycled Report Covers, Clear Pla...",West,Consumer,20-01-2020,First Class,Arizona,Binders,0.7,-23.7160,10,32.340

In [143]:
store[::-1]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448

In [147]:
store[::20]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
20,Furniture,Dover,United States,Seth Vernon,DAX,11-01-2020,US-2020-130092,19901,"DAX Value U-Channel Document Frames, Easel Back",East,Consumer,14-01-2020,First Class,Delaware,Furnishings,0.0,3.0814,2,9.940
40,Office Supplies,Scottsdale,United States,Toby Swindell,GBC,19-01-2020,US-2020-146591,85254,"GBC Standard Recycled Report Covers, Clear Pla...",West,Consumer,20-01-2020,First Class,Arizona,Binders,0.7,-23.7160,10,32.340
60,Furniture,Miami,United States,Tom Boeckenhauer,Ultra,21-01-2020,US-2020-110422,33180,Ultra Door Pull Handle,South,Consumer,23-01-2020,Second Class,Florida,Furnishings,0.2,4.1028,3,25.248
80,Office Supplies,New York City,United States,Jasper Cacioppo,Pressboard,28-01-2020,US-2020-100328,10024,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",East,Consumer,03-02-2020,Standard Class,New York,Binders,0.2,1.3257,1,3.928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10100,Office Supplies,Little Rock,United States,Monica Federle,Other,23-12-2023,US-2023-162670,72209,"Ink Jet Note and Greeting Cards, 8-1/2"" x 5-1/...",South,Corporate,28-12-2023,Second Class,Arkansas,Paper,0.0,20.6816,2,44.960
10120,Office Supplies,Seattle,United States,Alan Hwang,Office Impressions,24-12-2023,US-2023-147956,98105,Office Impressions Heavy Duty Welded Shelving ...,West,Consumer,31-12-2023,Standard Class,Washington,Storage,0.0,0.0000,6,1003.620
10140,Office Supplies,Los Angeles,United States,Fred Hopkins,Tennsco,25-12-2023,US-2023-121398,90008,"Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...",West,Corporate,29-12-2023,Standard Class,California,Storage,0.0,2.7062,2,270.620
10160,Office Supplies,New York City,United States,Jennifer Ferguson,Storex,28-12-2023,US-2023-164826,10024,Storex Dura Pro Binders,East,Consumer,04-01-2024,Standard Class,New York,Binders,0.2,11.2266,7,33.264
10180,Office Supplies,New York City,United States,Michael Chen,Other,29-12-2023,US-2023-102638,10035,Ideal Clamps,East,Consumer,31-12-2023,First Class,New York,Fasteners,0.0,2.9547,3,6.030

In [149]:
store[::-1].head()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930
10191,Office Supplies,Loveland,United States,Jill Matthias,Other,30-12-2023,US-2023-156720,80538,Bagged Rubber Bands,West,Consumer,03-01-2024,Standard Class,Colorado,Fasteners,0.2,-0.6048,3,3.024
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10189,Office Supplies,New York City,United States,Patrick O'Donnell,Wilson Jones,30-12-2023,US-2023-143259,10009,Wilson Jones Legal Size Ring Binders,East,Consumer,03-01-2024,Standard Class,New York,Binders,0.2,19.7910,3,52.776

In [151]:
store[::-1].tail()

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,04-01-2020,US-2020-112326,60540,SAFCO Boltless Steel Shelving,Central,Home Office,08-01-2020,Standard Class,Illinois,Storage,0.2,-64.7748,3,272.736
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,04-01-2020,US-2020-112326,60540,GBC Standard Plastic Binding Systems Combs,Central,Home Office,08-01-2020,Standard Class,Illinois,Binders,0.8,-5.4870,2,3.540
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448

In [153]:
store[::2]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,04-01-2020,US-2020-112326,60540,Avery 508,Central,Home Office,08-01-2020,Standard Class,Illinois,Labels,0.2,4.2717,3,11.784
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,05-01-2020,US-2020-141817,19143,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East,Consumer,12-01-2020,Standard Class,Pennsylvania,Art,0.2,4.8840,3,19.536
6,Office Supplies,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Handheld Barrel Pencil Sharpener,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.0,1.4796,2,5.480
8,Office Supplies,Henderson,United States,Maria Etezadi,Ibico,06-01-2020,US-2020-167199,42420,Ibico Hi-Tech Manual Binding System,South,Home Office,10-01-2020,Standard Class,Kentucky,Binders,0.0,274.4910,2,609.980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10184,Furniture,Quebec City,Canada,Bruce Galang,Other,29-12-2023,CA-2023-141531,G1B,Hand-Finished Solid Wood Document Frame,East,Consumer,02-01-2024,Standard Class,Quebec,Furnishings,0.0,20.5380,2,68.460
10186,Furniture,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,"Bush Westfield Collection Bookcases, Fully Ass...",East,Consumer,03-01-2024,Standard Class,New York,Bookcases,0.2,12.1176,4,323.136
10188,Office Supplies,Fairfield,United States,Erica Bern,Cardinal,30-12-2023,US-2023-115427,94533,"Cardinal Slant-D Ring Binder, Heavy Gauge Vinyl",West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,4.5188,2,13.904
10190,Office Supplies,Fairfield,United States,Erica Bern,GBC,30-12-2023,US-2023-115427,94533,GBC Binding covers,West,Corporate,03-01-2024,Standard Class,California,Binders,0.2,6.4750,2,20.720
10192,Technology,New York City,United States,Patrick O'Donnell,Other,30-12-2023,US-2023-143259,10009,Gear Head AU3700S Headset,East,Consumer,03-01-2024,Standard Class,New York,Phones,0.0,2.7279,7,90.930

In [155]:
store[::20]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
0,Office Supplies,Houston,United States,Darren Powers,Message Book,03-01-2020,US-2020-103800,77015,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central,Consumer,07-01-2020,Standard Class,Texas,Paper,0.2,5.5512,2,16.448
20,Furniture,Dover,United States,Seth Vernon,DAX,11-01-2020,US-2020-130092,19901,"DAX Value U-Channel Document Frames, Easel Back",East,Consumer,14-01-2020,First Class,Delaware,Furnishings,0.0,3.0814,2,9.940
40,Office Supplies,Scottsdale,United States,Toby Swindell,GBC,19-01-2020,US-2020-146591,85254,"GBC Standard Recycled Report Covers, Clear Pla...",West,Consumer,20-01-2020,First Class,Arizona,Binders,0.7,-23.7160,10,32.340
60,Furniture,Miami,United States,Tom Boeckenhauer,Ultra,21-01-2020,US-2020-110422,33180,Ultra Door Pull Handle,South,Consumer,23-01-2020,Second Class,Florida,Furnishings,0.2,4.1028,3,25.248
80,Office Supplies,New York City,United States,Jasper Cacioppo,Pressboard,28-01-2020,US-2020-100328,10024,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",East,Consumer,03-02-2020,Standard Class,New York,Binders,0.2,1.3257,1,3.928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10100,Office Supplies,Little Rock,United States,Monica Federle,Other,23-12-2023,US-2023-162670,72209,"Ink Jet Note and Greeting Cards, 8-1/2"" x 5-1/...",South,Corporate,28-12-2023,Second Class,Arkansas,Paper,0.0,20.6816,2,44.960
10120,Office Supplies,Seattle,United States,Alan Hwang,Office Impressions,24-12-2023,US-2023-147956,98105,Office Impressions Heavy Duty Welded Shelving ...,West,Consumer,31-12-2023,Standard Class,Washington,Storage,0.0,0.0000,6,1003.620
10140,Office Supplies,Los Angeles,United States,Fred Hopkins,Tennsco,25-12-2023,US-2023-121398,90008,"Tennsco Stur-D-Stor Boltless Shelving, 5 Shelv...",West,Corporate,29-12-2023,Standard Class,California,Storage,0.0,2.7062,2,270.620
10160,Office Supplies,New York City,United States,Jennifer Ferguson,Storex,28-12-2023,US-2023-164826,10024,Storex Dura Pro Binders,East,Consumer,04-01-2024,Standard Class,New York,Binders,0.2,11.2266,7,33.264
10180,Office Supplies,New York City,United States,Michael Chen,Other,29-12-2023,US-2023-102638,10035,Ideal Clamps,East,Consumer,31-12-2023,First Class,New York,Fasteners,0.0,2.9547,3,6.030

In [161]:
store[::-20]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
10193,Office Supplies,Charlottetown,Canada,Harry Olson,Wilson Jones,30-12-2023,CA-2023-143500,C0A,Wilson Jones Impact Binders,East,Consumer,03-01-2024,Standard Class,Prince Edward Island,Binders,0.2,-0.6048,3,3.024
10173,Furniture,Los Angeles,United States,James Galang,Global,29-12-2023,US-2023-118885,90049,"Global High-Back Leather Tilter, Burgundy",West,Consumer,02-01-2024,Standard Class,California,Chairs,0.2,-44.2764,4,393.568
10153,Furniture,Long Beach,United States,Jason Gross,Novimex,28-12-2023,US-2023-101322,90805,Novimex Turbo Task Chair,West,Corporate,31-12-2023,First Class,California,Chairs,0.2,-34.0704,6,340.704
10133,Office Supplies,Everett,United States,Giulietta Dortch,Other,25-12-2023,US-2023-162880,98208,Tuff Stuff Recycled Round Ring Binders,West,Corporate,29-12-2023,Standard Class,Washington,Binders,0.2,1.3978,1,3.856
10113,Office Supplies,New Bedford,United States,Nick Crebassa,Avery,24-12-2023,US-2023-148355,2740,"Avery Triangle Shaped Sheet Lifters, Black, 2/...",East,Corporate,28-12-2023,Standard Class,Massachusetts,Binders,0.0,6.1500,5,12.300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Office Supplies,Romeoville,United States,Delfina Latchford,Avery,06-02-2020,US-2020-108182,60441,"Avery Flip-Chart Easel Binder, Black",Central,Consumer,10-02-2020,Second Class,Illinois,Binders,0.8,-14.7708,2,8.952
73,Office Supplies,Alexandria,United States,Shirley Daniels,Eureka,26-01-2020,US-2020-155502,22304,"Eureka Recycled Copy Paper 8 1/2"" x 11"", Ream",South,Home Office,31-01-2020,Standard Class,Virginia,Paper,0.0,9.3312,3,19.440
53,Office Supplies,Smyrna,United States,Muhammed MacIntyre,GBC,20-01-2020,US-2020-147774,37167,GBC DocuBind TL200 Manual Binding Machine,South,Corporate,26-01-2020,Standard Class,Tennessee,Binders,0.7,-51.5154,1,67.194
33,Technology,Roswell,United States,Erica Hackney,Logitech,15-01-2020,US-2020-103366,30076,Logitech 910-002974 M325 Wireless Mouse for We...,South,Consumer,17-01-2020,First Class,Georgia,Accessories,0.0,65.9780,5,149.950
13,Technology,Henderson,United States,Maria Etezadi,GE,06-01-2020,US-2020-167199,42420,GE 30524EE4,South,Home Office,10-01-2020,Standard Class,Kentucky,Phones,0.0,113.6742,2,391.980

In [163]:
store[21:26]

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
21,Furniture,San Francisco,United States,Brian Dahlen,O'Sullivan,13-01-2020,US-2020-157147,94109,"O'Sullivan Elevations Bookcase, Cherry Finish",West,Consumer,18-01-2020,Standard Class,California,Bookcases,0.15,3.9294,3,333.999
22,Furniture,Mount Pleasant,United States,Natalie DeCherney,Global,13-01-2020,US-2020-109232,29464,Global Highback Leather Tilter in Burgundy,South,Consumer,16-01-2020,Second Class,South Carolina,Chairs,0.00,87.3504,6,545.940
23,Office Supplies,San Francisco,United States,Brian Dahlen,Other,13-01-2020,US-2020-157147,94109,4009 Highlighters by Sanford,West,Consumer,18-01-2020,Standard Class,California,Art,0.00,6.5670,5,19.900
24,Office Supplies,Newark,United States,Michael Moore,Avery,13-01-2020,US-2020-118192,43055,Avery Metallic Poly Binders,East,Consumer,18-01-2020,Standard Class,Ohio,Binders,0.70,-2.5212,2,3.438
25,Office Supplies,Bossier City,United States,Chris Selesnick,3-ring staple pack,13-01-2020,US-2020-162775,71111,3-ring staple pack,South,Corporate,15-01-2020,Second Class,Louisiana,Binders,0.00,2.7072,3,5.640

In [167]:
store['Customer Name'].head()

0    Darren Powers
1    Phillina Ober
2    Phillina Ober
3    Phillina Ober
4       Mick Brown
Name: Customer Name, dtype: object

In [169]:
store[['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
 'Product Name', 'Region']].head()

,Category,City,Country/Region,Customer Name,Manufacturer,Product Name,Region
0,Office Supplies,Houston,United States,Darren Powers,Message Book,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",Central
1,Office Supplies,Naperville,United States,Phillina Ober,GBC,GBC Standard Plastic Binding Systems Combs,Central
2,Office Supplies,Naperville,United States,Phillina Ober,Avery,Avery 508,Central
3,Office Supplies,Naperville,United States,Phillina Ober,SAFCO,SAFCO Boltless Steel Shelving,Central
4,Office Supplies,Philadelphia,United States,Mick Brown,Avery,Avery Hi-Liter EverBold Pen Style Fluorescent ...,East

In [171]:
store[4:8][['Category', 'City', 'Country/Region']]

          Category          City Country/Region
4  Office Supplies  Philadelphia  United States
5        Furniture     Henderson  United States
6  Office Supplies     Henderson  United States
7  Office Supplies        Athens  United States

In [177]:
store[['Category', 'City', 'Country/Region']][4:7]

          Category          City Country/Region
4  Office Supplies  Philadelphia  United States
5        Furniture     Henderson  United States
6  Office Supplies     Henderson  United States

In [181]:
store[2:30:5][['Category', 'City', 'Country/Region']]

           Category            City Country/Region
2   Office Supplies      Naperville  United States
7   Office Supplies          Athens  United States
12       Technology       Henderson  United States
17       Technology          Laredo  United States
22        Furniture  Mount Pleasant  United States
27  Office Supplies    Bossier City  United States

In [183]:
store.columns

Index(['Category', 'City', 'Country/Region', 'Customer Name', 'Manufacturer',
       'Order Date', 'Order ID', 'Postal Code', 'Product Name', 'Region',
       'Segment', 'Ship Date', 'Ship Mode', 'State/Province', 'Sub-Category',
       'Discount', 'Profit', 'Quantity', 'Sales'],
      dtype='object')

In [185]:
store1=store[['City','Customer Name','Product Name']][5:18]
store1

,City,Customer Name,Product Name
5,Henderson,Maria Etezadi,Global Deluxe High-Back Manager's Chair
6,Henderson,Maria Etezadi,Rogers Handheld Barrel Pencil Sharpener
7,Athens,Jack O'Briant,"Dixon Prang Watercolor Pencils, 10-Color Set w..."
8,Henderson,Maria Etezadi,Ibico Hi-Tech Manual Binding System
9,Henderson,Maria Etezadi,"Alliance Super-Size Bands, Assorted Sizes"
10,Henderson,Maria Etezadi,Southworth 25% Cotton Granite Paper & Envelopes
11,Los Angeles,Lycoris Saunders,Xerox 225
12,Henderson,Maria Etezadi,Wireless Extenders zBoost YX545 SOHO Signal Bo...
13,Henderson,Maria Etezadi,GE 30524EE4
14,Huntsville,Vivek Sundaresam,"Howard Miller 14-1/2"" Diameter Chrome Round Wa..."
15,Huntsville,Vivek Sundaresam,Acco Four Pocket Poly Ring Binder with Label H...
16,Laredo,Melanie Seite,Newell 312
17,Laredo,Melanie Seite,Memorex Micro Travel Drive 8 GB

In [189]:
store2=store[6:30:5]
store2

,Category,City,Country/Region,Customer Name,Manufacturer,Order Date,Order ID,Postal Code,Product Name,Region,Segment,Ship Date,Ship Mode,State/Province,Sub-Category,Discount,Profit,Quantity,Sales
6,Office Supplies,Henderson,United States,Maria Etezadi,Rogers,06-01-2020,US-2020-167199,42420,Rogers Handheld Barrel Pencil Sharpener,South,Home Office,10-01-2020,Standard Class,Kentucky,Art,0.00,1.4796,2,5.480
11,Office Supplies,Los Angeles,United States,Lycoris Saunders,Xerox,06-01-2020,US-2020-130813,90049,Xerox 225,West,Consumer,08-01-2020,Second Class,California,Paper,0.00,9.3312,3,19.440
16,Office Supplies,Laredo,United States,Melanie Seite,Newell,09-01-2020,US-2020-135405,78041,Newell 312,Central,Consumer,13-01-2020,Standard Class,Texas,Art,0.20,1.1680,2,9.344
21,Furniture,San Francisco,United States,Brian Dahlen,O'Sullivan,13-01-2020,US-2020-157147,94109,"O'Sullivan Elevations Bookcase, Cherry Finish",West,Consumer,18-01-2020,Standard Class,California,Bookcases,0.15,3.9294,3,333.999
26,Office Supplies,Bossier City,United States,Chris Selesnick,Other,13-01-2020,US-2020-162775,71111,Brown Kraft Recycled Envelopes,South,Corporate,15-01-2020,Second Class,Louisiana,Envelopes,0.00,25.4700,3,50.940

In [191]:
Store_num

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [193]:
Store_num.Profit * Store_num.Sales

0           91.306138
1          -19.423980
2           50.337713
3       -17666.419853
4           95.413824
             ...
10189     1044.489816
10190      134.162000
10191       -1.828915
10192      248.047947
10193       -1.828915
Length: 10194, dtype: float64

In [201]:
Store_num['myCalc'] = Store_num.Profit * Store_num.Sales

C:\Users\Sai Vamshi\AppData\Local\Temp\ipykernel_20288\1094312369.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Store_num['myCalc'] = Store_num.Profit * Store_num.Sales

In [203]:
Store_num['myCalc']

0           91.306138
1          -19.423980
2           50.337713
3       -17666.419853
4           95.413824
             ...
10189     1044.489816
10190      134.162000
10191       -1.828915
10192      248.047947
10193       -1.828915
Name: myCalc, Length: 10194, dtype: float64

In [205]:
Store_num

       Discount   Profit  Quantity    Sales        myCalc
0           0.2   5.5512         2   16.448     91.306138
1           0.8  -5.4870         2    3.540    -19.423980
2           0.2   4.2717         3   11.784     50.337713
3           0.2 -64.7748         3  272.736 -17666.419853
4           0.2   4.8840         3   19.536     95.413824
...         ...      ...       ...      ...           ...
10189       0.2  19.7910         3   52.776   1044.489816
10190       0.2   6.4750         2   20.720    134.162000
10191       0.2  -0.6048         3    3.024     -1.828915
10192       0.0   2.7279         7   90.930    248.047947
10193       0.2  -0.6048         3    3.024     -1.828915

[10194 rows x 5 columns]

In [207]:
Store_num.head()

   Discount   Profit  Quantity    Sales        myCalc
0       0.2   5.5512         2   16.448     91.306138
1       0.8  -5.4870         2    3.540    -19.423980
2       0.2   4.2717         3   11.784     50.337713
3       0.2 -64.7748         3  272.736 -17666.419853
4       0.2   4.8840         3   19.536     95.413824

In [215]:
Store_num.drop('myClac', axis=1)

       Discount   Profit  Quantity    Sales        myCalc
0           0.2   5.5512         2   16.448     91.306138
1           0.8  -5.4870         2    3.540    -19.423980
2           0.2   4.2717         3   11.784     50.337713
3           0.2 -64.7748         3  272.736 -17666.419853
4           0.2   4.8840         3   19.536     95.413824
...         ...      ...       ...      ...           ...
10189       0.2  19.7910         3   52.776   1044.489816
10190       0.2   6.4750         2   20.720    134.162000
10191       0.2  -0.6048         3    3.024     -1.828915
10192       0.0   2.7279         7   90.930    248.047947
10193       0.2  -0.6048         3    3.024     -1.828915

[10194 rows x 5 columns]

In [217]:
Store_num=Store_num.drop('myCalc', axis=1)

In [219]:
Store_num

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [223]:
Store_num.columns[2]

'Quantity'

In [225]:
Store_num.Quantity<2

0        False
1        False
2        False
3        False
4        False
         ...
10189    False
10190    False
10191    False
10192    False
10193    False
Name: Quantity, Length: 10194, dtype: bool

In [229]:
filter=Store_num.Quantity<2
filter

0        False
1        False
2        False
3        False
4        False
         ...
10189    False
10190    False
10191    False
10192    False
10193    False
Name: Quantity, Length: 10194, dtype: bool

In [231]:
Store_num[filter]

       Discount   Profit  Quantity    Sales
10          0.0   3.0084         1    6.540
18          0.0  21.2954         1   51.940
19          0.0   1.3583         1    2.890
53          0.7 -51.5154         1   67.194
57          0.0   4.0542         1   13.980
...         ...      ...       ...      ...
10166       0.0   1.9260         1    4.280
10167       0.2 -12.9568         1   64.784
10174       0.0  87.2842         1  300.980
10177       0.0  10.0282         1   34.580
10178       0.0   5.8891         1   12.530

[933 rows x 4 columns]

In [233]:
Store_num[filter].head()

    Discount   Profit  Quantity   Sales
10       0.0   3.0084         1   6.540
18       0.0  21.2954         1  51.940
19       0.0   1.3583         1   2.890
53       0.7 -51.5154         1  67.194
57       0.0   4.0542         1  13.980

In [235]:
Store_num[filter][2:10]

    Discount   Profit  Quantity    Sales
19       0.0   1.3583         1    2.890
53       0.7 -51.5154         1   67.194
57       0.0   4.0542         1   13.980
62       0.0   3.7900         1    9.480
64       0.0   3.1100         1    6.480
79       0.0  14.3075         1   57.230
80       0.2   1.3257         1    3.928
96       0.0  42.0186         1  161.610

In [237]:
filter1=Store_num.Sales>10
filter1

0         True
1        False
2         True
3         True
4         True
         ...
10189     True
10190     True
10191    False
10192     True
10193    False
Name: Sales, Length: 10194, dtype: bool

In [241]:
Store_num[filter1]

       Discount    Profit  Quantity     Sales
0           0.2    5.5512         2    16.448
2           0.2    4.2717         3    11.784
3           0.2  -64.7748         3   272.736
4           0.2    4.8840         3    19.536
5           0.0  746.4078         9  2573.820
...         ...       ...       ...       ...
10187       0.0   56.5110         2   209.300
10188       0.2    4.5188         2    13.904
10189       0.2   19.7910         3    52.776
10190       0.2    6.4750         2    20.720
10192       0.0    2.7279         7    90.930

[8796 rows x 4 columns]

In [243]:
filter&filter1

0        False
1        False
2        False
3        False
4        False
         ...
10189    False
10190    False
10191    False
10192    False
10193    False
Length: 10194, dtype: bool

In [247]:
Store_num[filter&filter1]

       Discount   Profit  Quantity    Sales
18          0.0  21.2954         1   51.940
53          0.7 -51.5154         1   67.194
57          0.0   4.0542         1   13.980
79          0.0  14.3075         1   57.230
96          0.0  42.0186         1  161.610
...         ...      ...       ...      ...
10129       0.7 -10.4184         1   13.023
10167       0.2 -12.9568         1   64.784
10174       0.0  87.2842         1  300.980
10177       0.0  10.0282         1   34.580
10178       0.0   5.8891         1   12.530

[564 rows x 4 columns]

In [251]:
Store_num[(Store_num.Quantity>5) &(Store_num.Sales>30)]

       Discount    Profit  Quantity     Sales
5           0.0  746.4078         9  2573.820
22          0.0   87.3504         6   545.940
28          0.2   13.0928         7    37.408
29          0.0   34.3548         6   572.580
31          0.0  258.6960         6   646.740
...         ...       ...       ...       ...
10165       0.0   34.7760         7    72.450
10172       0.0  314.0384         8  1207.840
10175       0.0   37.4144         8   101.120
10183       0.0   35.4144         8    99.120
10192       0.0    2.7279         7    90.930

[1569 rows x 4 columns]

In [271]:
Store_num[(Store_num.Quantity>5) &(Store_num.Sales>30) &(Store_num.Profit>50)]

       Discount     Profit  Quantity     Sales
5           0.0   746.4078         9  2573.820
22          0.0    87.3504         6   545.940
31          0.0   258.6960         6   646.740
59          0.0   181.9818         7   699.930
65          0.0    58.6600        10   209.500
...         ...        ...       ...       ...
10066       0.0   412.5394         7  1586.690
10091       0.4    94.4937         7   629.958
10121       0.2  1007.9832         6  2879.952
10137       0.0   301.9680         6   629.100
10172       0.0   314.0384         8  1207.840

[574 rows x 4 columns]

In [335]:
len(Store_num[(Store_num.Quantity>5) &(Store_num.Sales>30) &(Store_num.Profit>50)])

574

In [273]:
Store_num[(Store_num.Quantity>5) &(Store_num.Sales>30) &(Store_num.Profit>50)].head()

    Discount    Profit  Quantity    Sales
5        0.0  746.4078         9  2573.82
22       0.0   87.3504         6   545.94
31       0.0  258.6960         6   646.74
59       0.0  181.9818         7   699.93
65       0.0   58.6600        10   209.50

In [275]:
Store_num[(Store_num.Quantity>5) &(Store_num.Sales>30) &(Store_num.Profit>50)].tail()

       Discount     Profit  Quantity     Sales
10066       0.0   412.5394         7  1586.690
10091       0.4    94.4937         7   629.958
10121       0.2  1007.9832         6  2879.952
10137       0.0   301.9680         6   629.100
10172       0.0   314.0384         8  1207.840

In [277]:
Store_num.Sales==60

0        False
1        False
2        False
3        False
4        False
         ...
10189    False
10190    False
10191    False
10192    False
10193    False
Name: Sales, Length: 10194, dtype: bool

In [331]:
Store_num[Store_num.Sales!=60]

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [285]:
Store_num[Store_num.Sales>60]

       Discount    Profit  Quantity     Sales
3           0.2  -64.7748         3   272.736
5           0.0  746.4078         9  2573.820
8           0.0  274.4910         2   609.980
12          0.0  204.1092         4   755.960
13          0.0  113.6742         2   391.980
...         ...       ...       ...       ...
10183       0.0   35.4144         8    99.120
10184       0.0   20.5380         2    68.460
10186       0.2   12.1176         4   323.136
10187       0.0   56.5110         2   209.300
10192       0.0    2.7279         7    90.930

[4879 rows x 4 columns]

In [317]:
len(Store_num[Store_num.Sales>60])

4879

In [287]:
Store_num[Store_num.Sales>60][0:10]

    Discount    Profit  Quantity     Sales
3       0.20  -64.7748         3   272.736
5       0.00  746.4078         9  2573.820
8       0.00  274.4910         2   609.980
12      0.00  204.1092         4   755.960
13      0.00  113.6742         2   391.980
14      0.60  -53.7096         3    76.728
21      0.15    3.9294         3   333.999
22      0.00   87.3504         6   545.940
29      0.00   34.3548         6   572.580
30      0.00  238.6530         5  1325.850

In [311]:
Store_num

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[10194 rows x 4 columns]

In [291]:
Store_num[Store_num.Profit<90]

       Discount   Profit  Quantity    Sales
0           0.2   5.5512         2   16.448
1           0.8  -5.4870         2    3.540
2           0.2   4.2717         3   11.784
3           0.2 -64.7748         3  272.736
4           0.2   4.8840         3   19.536
...         ...      ...       ...      ...
10189       0.2  19.7910         3   52.776
10190       0.2   6.4750         2   20.720
10191       0.2  -0.6048         3    3.024
10192       0.0   2.7279         7   90.930
10193       0.2  -0.6048         3    3.024

[9193 rows x 4 columns]

In [337]:
len(Store_num[Store_num.Profit<90])

9193

In [299]:
len(Store_num.columns)

4

In [341]:
Store_num[Store_num.Quantity==2]

       Discount    Profit  Quantity    Sales
0           0.2    5.5512         2   16.448
1           0.8   -5.4870         2    3.540
6           0.0    1.4796         2    5.480
8           0.0  274.4910         2  609.980
13          0.0  113.6742         2  391.980
...         ...       ...       ...      ...
10181       0.0  100.6560         2  209.700
10184       0.0   20.5380         2   68.460
10187       0.0   56.5110         2  209.300
10188       0.2    4.5188         2   13.904
10190       0.2    6.4750         2   20.720

[2440 rows x 4 columns]

In [345]:
len(Store_num[Store_num.Quantity==3])

2435

In [349]:
Store_num.Quantity.unique()

array([ 2,  3,  9,  4,  1,  7,  6,  5, 10,  8, 13, 14, 12, 11])

In [351]:
Store_num[Store_num.Quantity==12]

      Discount    Profit  Quantity     Sales
190        0.0    6.6240        12    82.800
367        0.4    8.3916        12    71.928
542        0.2  125.2692        12  1113.504
1444       0.2   15.5376        12    47.808
1849       0.2  135.4068        12  3610.848
3002       0.0   10.0128        12    35.760
3353       0.0  561.5640        12  1871.880
3841       0.2   42.5880        12   681.408
4171       0.0  167.8080        12   364.800
4926       0.2   18.7224        12    51.648
5343       0.0   23.4192        12   167.280
5915       0.0    0.9336        12    93.360
6096       0.2   15.7992        12    43.584
6308       0.2   21.8880        12    58.368
6319       0.0   11.3100        12    39.000
6594       0.0   36.9288        12    80.280
7682       0.2   42.5880        12   681.408
7986       0.0    1.6752        12    83.760
9067       0.0  130.7520        12   435.840
9285       0.2   20.9148        12  1673.184
9636       0.0  375.4296        12  1443.960
9687       0.4 -619.5960        12  2065.320
9716       0.0   31.0992        12    70.680

In [353]:
Store_num.Profit/Store_num.Sales

0        0.3375
1       -1.5500
2        0.3625
3       -0.2375
4        0.2500
          ...
10189    0.3750
10190    0.3125
10191   -0.2000
10192    0.0300
10193   -0.2000
Length: 10194, dtype: float64

In [357]:
Store_num['P/S']=Store_num.Profit/Store_num.Sales
Store_num

       Discount   Profit  Quantity    Sales     P/S
0           0.2   5.5512         2   16.448  0.3375
1           0.8  -5.4870         2    3.540 -1.5500
2           0.2   4.2717         3   11.784  0.3625
3           0.2 -64.7748         3  272.736 -0.2375
4           0.2   4.8840         3   19.536  0.2500
...         ...      ...       ...      ...     ...
10189       0.2  19.7910         3   52.776  0.3750
10190       0.2   6.4750         2   20.720  0.3125
10191       0.2  -0.6048         3    3.024 -0.2000
10192       0.0   2.7279         7   90.930  0.0300
10193       0.2  -0.6048         3    3.024 -0.2000

[10194 rows x 5 columns]

In [361]:
Store_num['P/S']

0        0.3375
1       -1.5500
2        0.3625
3       -0.2375
4        0.2500
          ...
10189    0.3750
10190    0.3125
10191   -0.2000
10192    0.0300
10193   -0.2000
Name: P/S, Length: 10194, dtype: float64

In [365]:
Store_num[['Profit','Sales','P/S']]

        Profit    Sales     P/S
0       5.5512   16.448  0.3375
1      -5.4870    3.540 -1.5500
2       4.2717   11.784  0.3625
3     -64.7748  272.736 -0.2375
4       4.8840   19.536  0.2500
...        ...      ...     ...
10189  19.7910   52.776  0.3750
10190   6.4750   20.720  0.3125
10191  -0.6048    3.024 -0.2000
10192   2.7279   90.930  0.0300
10193  -0.6048    3.024 -0.2000

[10194 rows x 3 columns]